version: '3'
networks:
  localnetwork:
services:
  db:
    image: "mysql:8.4"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=betterPasswordThanDefaultAtleast1001#
      - MYSQL_DATABASE=auth
      - MYSQL_ROOT_USER=root
      - MYSQL_PASSWORD=betterPasswordThanDefaultAtleast1001#
    ports:
      - 3307:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - localnetwork
  web:
    build: .
    environment: 
      - DB_SERVER=db
      - DB_USER=root
      - DB_PASSWORD=betterPasswordThanDefaultAtleast1001#
      - DB_NAME=auth
    ports:
      - "8001:80"
    networks:
      - localnetwork
